cmf_routing:
    chain:
        routers_by_id:
            router.default: 200
            cmf_routing.dynamic_router: 100
    dynamic:
        enabled: true
        persistence:
            orm: ~
        route_provider_service_id: positibe_orm_routing.route.provider
        generic_controller: PositibeOrmRoutingBundle:GenericContent:index

parameters:
    auto_routing:
