parameters:
    positibe_orm_routing.route_entity.class: Positibe\Bundle\OrmRoutingBundle\Entity\Route
    stof_doctrine_extensions.event_listener.locale.class: Positibe\Bundle\OrmRoutingBundle\EventListener\LocaleListener

services:
    positibe_orm_routing.form.positibe_route_locale_type:
        class: Positibe\Bundle\OrmRoutingBundle\Form\Type\RoutePermalinkType
        arguments: [@positibe_orm_routing.route_builder, %locale%]
        tags:
            - { name: form.type, alias: positibe_route_permalink }

    positibe_orm_routing.route.provider:
        class: Positibe\Bundle\OrmRoutingBundle\Routing\Provider\OrmRouteProvider
        arguments: [@doctrine, @cmf_routing.orm_candidates, %positibe_orm_routing.route_entity.class%]
        calls:
            - [ setManagerName, [%cmf_routing.dynamic.persistence.orm.manager_name%] ]
            - [ setRouteCollectionLimit, [%cmf_routing.route_collection_limit%] ]

    positibe_orm_routing.route_builder:
        class: Positibe\Bundle\OrmRoutingBundle\Builder\RouteBuilder

    positibe_orm_routing.route_content_enhancer:
        class: Positibe\Bundle\OrmRoutingBundle\Routing\Enhancer\RouteContentEnhancer
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - { name: dynamic_router_route_enhancer, priority: 500 }
