parameters:
    positibe_routing.route_entity.class: Positibe\Bundle\CmfRoutingExtraBundle\Entity\AutoRoute

services:
    positibe_routing.form.positibe_route_locale_type:
        class: Positibe\Bundle\CmfRoutingExtraBundle\Form\Type\RoutePermalinkType
        arguments: ["@positibe_routing.route_factory", "%locale%"]
        tags:
            - { name: form.type }

    positibe_routing.route_factory:
        class: Positibe\Bundle\CmfRoutingExtraBundle\Factory\RouteFactory
        arguments: ["@cmf_routing.content_repository"]

    positibe_routing_auto.auto_routing_entity_listener:
        class: Positibe\Bundle\CmfRoutingExtraBundle\EventListener\RoutingAutoEntityListener
        arguments: ["@service_container"]
        tags:
            - { name: doctrine.orm.entity_listener }

    positibe_routing_auto.adapter:
        class: Positibe\Bundle\CmfRoutingExtraBundle\RoutingAuto\Adapter\OrmAdapter
        arguments: ["@doctrine.orm.entity_manager", "@positibe_routing.route_factory", "%locale%", "%locales%"]
        tags:
            - { name: cmf_routing_auto.adapter, alias: positibe_doctrine_orm }